config/routes.rb
Rails.application.routes.draw do
  resources :money
root 'money#index'

end

app/models/money.rb
class Money < ActiveRecord::Base

  def self.balance
    positive = []
    negative = []
    self.all.each do |x|
      positive << x.amount.to_f if x.deposit == "t"
      negative << x.amount.to_f if x.deposit == "f"
    end
      total = positive.sum - negative.sum
  end


  def self.total_transactions
    self.count
  end

  def self.current_monthly_spent
    current = Time.now.mon
    money_spent = []
    self.all.each do |x|
      money_spent << x.amount.to_f if x.date.mon == current && x.deposit == "f"
    end
    money_spent.sum
  end

  def self.previous_monthly_spent
    previous = Time.now.mon - 1
    money_spent = []
    self.all.each do |x|
      money_spent << x.amount.to_f if x.date.mon == previous && x.deposit == "f"
    end
    money_spent.sum
  end

  def self.current_largest_spent_amount
    money_spent = []
    current = Time.now.mon
    self.all.each do |x|
      money_spent << x.amount.to_f if x.date.mon == current && x.deposit == "f"
    end
    largest = Money.find_by amount: money_spent.max
    largest.amount
  end

  def self.current_largest_spent_amount_id
    money_spent = []
    current = Time.now.mon
    self.all.each do |x|
      money_spent << x.amount.to_f if x.date.mon == current && x.deposit == "f"
    end
    largest = Money.find_by amount: money_spent.max
    largest.id
  end

  def self.total_largest_spent_amount
    money_spent = []
    self.all.each do |x|
      money_spent << x.amount.to_f if x.deposit == "f"
    end
    largest = Money.find_by amount: money_spent.max
    largest.amount
  end

  def self.total_largest_spent_amount_org
    money_spent = []
    self.all.each do |x|
      money_spent << x.amount.to_f if x.deposit == "f"
    end
    largest = Money.find_by amount: money_spent.max
    largest.organization
  end

  # def self.overall_most_money_spent
  #   money_spent = []
  #   byebug
  #   self.all.each do |x|
  #     byebug
  #   end
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :set_money, only: [:show, :edit, :update, :destroy]

  # GET /money
  # GET /money.json
  def index
    @money = Money.all
    @balance = Money.balance.round(2)
    @total_transactions = Money.total_transactions
    @current_monthly_spent = Money.current_monthly_spent
    @previous_monthly_spent = Money.previous_monthly_spent
    @current_largest_spent_amount = Money.current_largest_spent_amount
    @current_largest_spent_amount_id = Money.current_largest_spent_amount_id
    @total_largest_spent_amount = Money.total_largest_spent_amount
    @total_largest_spent_amount_org = Money.total_largest_spent_amount_org
  end

  # GET /money/1
  # GET /money/1.json
  def show
  end

  # GET /money/new
  def new
    @money = Money.new
  end

  # GET /money/1/edit
  def edit
  end

  # POST /money
  # POST /money.json
  def create
    @money = Money.new(money_params)

    respond_to do |format|
      if @money.save
        format.html { redirect_to @money, notice: 'Money was successfully created.' }
        format.json { render :show, status: :created, location: @money }
      else
        format.html { render :new }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money/1
  # PATCH/PUT /money/1.json
  def update
    respond_to do |format|
      if @money.update(money_params)
        format.html { redirect_to @money, notice: 'Money was successfully updated.' }
        format.json { render :show, status: :ok, location: @money }
      else
        format.html { render :edit }
        format.json { render json: @money.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /money/1
  # DELETE /money/1.json
  def destroy
    @money.destroy
    respond_to do |format|
      format.html { redirect_to money_index_url, notice: 'Money was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money
      @money = Money.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def money_params
      params.require(:money).permit(:amount, :deposit, :organization, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallety</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/money/_form.html.erb
<%= form_for(@money) do |f| %>
  <% if @money.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@money.errors.count, "error") %> prohibited this money from being saved:</h2>

      <ul>
      <% @money.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :deposit %><br>
    <%= f.text_field :deposit %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/money/dashboard.html.erb
hi hi hi

app/views/money/edit.html.erb
<h1>Editing Money</h1>

<%= render 'form' %>

<%= link_to 'Show', @money %> |
<%= link_to 'Back', money_index_path %>

app/views/money/index.html.erb
<p id="notice"><%= notice %></p>


<% unless @balance >= 0 %>
<h1 style="background-color: red;font-weight:bold ">You are negative monies!</h1>
<% end %>


<h1>Listing Money</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Deposit</th>
      <th>Organization</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @money.each do |money| %>
      <tr>
        <td><%= money.amount %></td>
        <td><%= money.deposit %></td>
        <td><%= money.organization %></td>
        <td><%= money.date %></td>
        <td><%= link_to 'Show', money %></td>
        <td><%= link_to 'Edit', edit_money_path(money) %></td>
        <td><%= link_to 'Destroy', money, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Money', new_money_path %>
<% unless @balance >= 0 %>
<h1 style="background-color: red;font-weight:bold ">You are negative monies!</h1>
<% end %>

<h1>Your transaction count is : <%= @total_transactions %> </h1>
<br>
<h1>Your current balance is : $<%= @balance %> </h1>
<br>
<h1>Amount you've spent this month is: $<%= @current_monthly_spent %> </h1>
<h1>Amount you've spent last month was: $<%= @previous_monthly_spent %> </h1>
<br>
<h1>Your largest transaction amount this month was: $<%= @current_largest_spent_amount %> </h1>
<h2>The ID for that transaction is :<%= @current_largest_spent_amount_id %> </h2>
<br>
<h1>Your largest transaction amount ever is: $<%= @total_largest_spent_amount %> </h1>
<h2>The organization for that transaction is : <%= @total_largest_spent_amount_org %> </h2>

app/views/money/new.html.erb
<h1>New Money</h1>

<%= render 'form' %>

<%= link_to 'Back', money_index_path %>

app/views/money/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @money.amount %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @money.deposit %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @money.organization %>
</p>

<p>
  <strong>Date:</strong>
  <%= @money.date %>
</p>

<%= link_to 'Edit', edit_money_path(@money) %> |
<%= link_to 'Back', money_index_path %>